# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aura.negotiation.v1 import negotiation_pb2 as aura_dot_negotiation_dot_v1_dot_negotiation__pb2


class NegotiationServiceStub(object):
    """Service for handling negotiations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Negotiate = channel.unary_unary(
                '/aura.negotiation.v1.NegotiationService/Negotiate',
                request_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.NegotiateRequest.SerializeToString,
                response_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.NegotiateResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/aura.negotiation.v1.NegotiationService/Search',
                request_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.SearchRequest.SerializeToString,
                response_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/aura.negotiation.v1.NegotiationService/GetSystemStatus',
                request_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.GetSystemStatusRequest.SerializeToString,
                response_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.GetSystemStatusResponse.FromString,
                _registered_method=True)
        self.CheckDealStatus = channel.unary_unary(
                '/aura.negotiation.v1.NegotiationService/CheckDealStatus',
                request_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.CheckDealStatusRequest.SerializeToString,
                response_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.CheckDealStatusResponse.FromString,
                _registered_method=True)


class NegotiationServiceServicer(object):
    """Service for handling negotiations.
    """

    def Negotiate(self, request, context):
        """RPC method for negotiating offers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """RPC method for retrieving system status and metrics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDealStatus(self, request, context):
        """RPC method for checking crypto payment status and retrieving secrets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NegotiationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Negotiate': grpc.unary_unary_rpc_method_handler(
                    servicer.Negotiate,
                    request_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.NegotiateRequest.FromString,
                    response_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.NegotiateResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.SearchRequest.FromString,
                    response_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.SearchResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.GetSystemStatusRequest.FromString,
                    response_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.GetSystemStatusResponse.SerializeToString,
            ),
            'CheckDealStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDealStatus,
                    request_deserializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.CheckDealStatusRequest.FromString,
                    response_serializer=aura_dot_negotiation_dot_v1_dot_negotiation__pb2.CheckDealStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.negotiation.v1.NegotiationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.negotiation.v1.NegotiationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NegotiationService(object):
    """Service for handling negotiations.
    """

    @staticmethod
    def Negotiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.negotiation.v1.NegotiationService/Negotiate',
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.NegotiateRequest.SerializeToString,
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.NegotiateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.negotiation.v1.NegotiationService/Search',
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.SearchRequest.SerializeToString,
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.negotiation.v1.NegotiationService/GetSystemStatus',
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.GetSystemStatusRequest.SerializeToString,
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.GetSystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckDealStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.negotiation.v1.NegotiationService/CheckDealStatus',
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.CheckDealStatusRequest.SerializeToString,
            aura_dot_negotiation_dot_v1_dot_negotiation__pb2.CheckDealStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
