import os
import subprocess  # nosec B404
import sys
from pathlib import Path
from typing import Any

import structlog
from hatchling.builders.hooks.plugin.interface import BuildHookInterface

logger = structlog.get_logger(__name__)


class CustomBuildHook(BuildHookInterface):
    def initialize(self, version: str, build_data: Any) -> None:
        project_root = Path(self.root)

        possible_proto_paths = [
            project_root / "proto",
            project_root.parent.parent / "proto",
        ]

        proto_dir = None
        for p in possible_proto_paths:
            if p.exists():
                proto_dir = p.absolute()
                break

        if not proto_dir:
            logger.warning("DNA Source (proto) not found in: %s", possible_proto_paths)
            return

        out_dir = project_root / "src" / "aura_core" / "gen"
        out_dir.mkdir(parents=True, exist_ok=True)

        logger.info("🧬 Bio-Digital Transcription starting...")

        proto_file = proto_dir / "aura" / "dna" / "v1" / "dna.proto"

        try:
            result = subprocess.run(  # nosec B603
                [
                    sys.executable,
                    "-m",
                    "grpc_tools.protoc",
                    f"--proto_path={proto_dir}",
                    f"--python_betterproto_out={out_dir}",
                    str(proto_file),
                ],
                capture_output=True,
                text=True,
            )

            if result.returncode != 0:
                logger.error(f"❌ Protoc Error:\n{result.stderr}")
                raise RuntimeError("Protoc failed")

            google_shim_dir = Path(out_dir) / "aura" / "dna" / "google"
            google_shim_dir.mkdir(parents=True, exist_ok=True)

            shim_file = google_shim_dir / "__init__.py"
            with open(shim_file, "w") as f:
                f.write("# 🧬 Aura Hive Google Shim for Betterproto\n")
                f.write("from betterproto.lib.google import protobuf\n")

            self._ensure_init_files(out_dir)

            logger.info("✅ DNA expressed and packages initialized.")

        except Exception as e:
            logger.critical("Critical Transcription failure", exc_info=True)
            raise e

    def _ensure_init_files(self, base_path: Path) -> None:
        for root, dirs, _ in os.walk(base_path):
            for d in dirs:
                dir_path = Path(root) / d
                init_file = dir_path / "__init__.py"
                if not init_file.exists():
                    with open(init_file, "w") as f:
                        f.write("# Generated by Aura Hive Build System\n")

            root_init = Path(root) / "__init__.py"
            if not root_init.exists():
                with open(root_init, "w") as f:
                    f.write("# Root Gen Package\n")
