import os
import subprocess  # nosec B404
import sys
from pathlib import Path
from typing import Any

import structlog
from hatchling.builders.hooks.plugin.interface import BuildHookInterface

logger = structlog.get_logger(__name__)


class CustomBuildHook(BuildHookInterface):
    def initialize(self, version: str, build_data: Any) -> None:
        project_root = Path(self.root)

        possible_proto_paths = [
            project_root / "proto",
            project_root.parent.parent / "proto",
        ]

        proto_dir = None
        for p in possible_proto_paths:
            if p.exists():
                proto_dir = p.absolute()
                break

        if not proto_dir:
            logger.warning("DNA Source (proto) not found in: %s", possible_proto_paths)
            return

        out_dir = project_root / "src" / "aura_core" / "gen"
        out_dir.mkdir(parents=True, exist_ok=True)

        logger.info("🧬 Bio-Digital Transcription starting...")

        proto_files = list(proto_dir.rglob("*.proto"))

        try:
            result = subprocess.run(  # nosec B603
                [
                    sys.executable,
                    "-m",
                    "grpc_tools.protoc",
                    f"--proto_path={proto_dir}",
                    f"--python_betterproto_out={out_dir}",
                    *[str(p) for p in proto_files],
                ],
                capture_output=True,
                text=True,
            )

            if result.returncode != 0:
                logger.error(f"❌ Protoc Error:\n{result.stderr}")
                raise RuntimeError("Protoc failed")

            # SSA Alignment: Ensure modular structure
            # Transform v1.py to v1/__init__.py and inject shims
            for root, dirs, files in os.walk(out_dir):
                for f in files:
                    if f.endswith(".py") and f != "__init__.py":
                        module_name = f[:-3]
                        module_path = Path(root) / f
                        package_dir = Path(root) / module_name

                        # Only do this for aura packages (nested)
                        if "aura" in str(module_path):
                            package_dir.mkdir(exist_ok=True)
                            init_file = package_dir / "__init__.py"
                            module_path.rename(init_file)
                            logger.debug("Modularized %s", module_name)

                if "google" in dirs:
                    # If we modularized v1, google might be a sibling of v1 or inside it.
                    # betterproto usually puts it as a sibling of the generated file.
                    # But if we move the file into v1/, we should move google too if it was meant to be relative.
                    pass

            # Final recursive shim and init injection
            self._inject_shims(out_dir)
            self._ensure_init_files(out_dir)

            logger.info("✅ DNA expressed and packages initialized.")

        except Exception as e:
            logger.critical("Critical Transcription failure", exc_info=True)
            raise e

    def _inject_shims(self, base_path: Path) -> None:
        for root, dirs, _ in os.walk(base_path):
            if "google" in dirs:
                google_shim_dir = Path(root) / "google"
                google_shim_dir.mkdir(parents=True, exist_ok=True)
                shim_file = google_shim_dir / "__init__.py"
                with open(shim_file, "w") as f:
                    f.write("# 🧬 Aura Hive Google Shim for Betterproto\n")
                    f.write("from betterproto.lib.google import protobuf\n")

    def _ensure_init_files(self, base_path: Path) -> None:
        for root, dirs, _ in os.walk(base_path):
            for d in dirs:
                dir_path = Path(root) / d
                init_file = dir_path / "__init__.py"
                if not init_file.exists():
                    with open(init_file, "w") as f:
                        f.write("# Generated by Aura Hive Build System\n")

            root_init = Path(root) / "__init__.py"
            if not root_init.exists():
                with open(root_init, "w") as f:
                    f.write("# Root Gen Package\n")
