apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-grafana-datasources"
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: Prometheus
        type: prometheus
        url: "http://monitoring-kube-prometheus-prometheus.monitoring:9090"
        access: proxy
        isDefault: true
      - name: Jaeger
        uid: Jaeger
        type: jaeger
        url: "http://aura-jaeger.monitoring:16686"
        access: proxy
      - name: Loki
        uid: Loki
        type: loki
        url: "http://loki.monitoring:3100"
        access: proxy
        jsonData:
          derivedFields:
            - datasourceUid: Jaeger
              matcherRegex: '"trace_id":\s*"(\w+)"'
              name: trace_id
              url: '${__value.raw}'
