{{- if .Values.loki.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Release.Name }}-promtail"
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: "{{ .Release.Name }}-promtail"
      containers:
      - name: promtail
        image: grafana/promtail:2.9.2
        args:
        - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
        - name: logs
          mountPath: /var/log
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: config
          mountPath: /etc/promtail
      volumes:
      - name: logs
        hostPath:
          path: /var/log
      - name: pods
        hostPath:
          path: /var/log/pods
      - name: config
        configMap:
          name: "{{ .Release.Name }}-promtail-config"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-promtail"
  labels:
    app: promtail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-promtail"
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-promtail"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-promtail"
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-promtail"
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-promtail-config"
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push

    scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - replacement: /var/log/pods/$1/*.log
        separator: /
        source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
        target_label: __path__
{{- end }}
