apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-vision-cortex"
  labels:
    {{- include "aura.labels" . | nindent 4 }}
    app: vision-cortex
spec:
  type: ClusterIP
  selector:
    app: frpc
    component: tunnel
  ports:
    - port: 11435
      targetPort: 11435
      protocol: TCP
      name: vision-api
